name: app_mitigasi_bencana
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.12
  syncfusion_flutter_pdfviewer: ^22.2.10
  cupertino_icons: ^1.0.2
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.4.0
  location: ^5.0.3
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_bacground: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo_foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/report.png
    - assets/images/map.png
    - assets/images/book.png
    - assets/images/books/book1.png
    - assets/pdf/book1.pdf
    - assets/images/books/book2.png
    - assets/pdf/book2.pdf
    - assets/images/books/book3.png
    - assets/pdf/book3.pdf
    - assets/images/books/book4.png
    - assets/pdf/book4.pdf
    - assets/images/books/book5.png
    - assets/pdf/book5.pdf
    
